# Generated by Django 4.1.7 on 2023-03-24 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("produit", "0002_produit"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="produit",
            options={"ordering": ("-date_added",)},
        ),
    ]
