# Generated by Django 4.1.7 on 2023-03-24 23:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("order", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order",
            old_name="strip_token",
            new_name="stripe_token",
        ),
    ]
